### ISSUE TITLE
Bot scripts for experiments

### ISSUE THREAD

**Issue by wakamex** [delvtech/hyperdrive-infra#69]
Set up environment for easily running experiments with bots, using scripts

1. move existing code to [fork](https://github.com/wakamex/elf-simulations)
2. apply custom config in commits (was previously manually applying but not committing)
3. recreate logging experience from previous version
4. create deterministic bots for testing
5. fix bug I hadn't yet pushed upstream
6. fix bugs introduced in latest version
7. allow running bots outside of elf-sims repo
8. document workflows for using bots

Progress:

1. done by creating the repo and pushing branches to it
2. done in [custom config](https://github.com/delvtech/elf-simulations/commit/2df32694769e717d16914c73e463136614bf8fb2) and [custom agent defaults](https://github.com/delvtech/elf-simulations/commit/287d6d57258bc07fa0f1b40a28c53271212d35d3)
3. done in [better wallet logging](https://github.com/delvtech/elf-simulations/commit/94ac330e06033c89daa50058025f2a7c9a0ee2f0) and [more terse logging](https://github.com/delvtech/elf-simulations/commit/4487836dfa9e3610329362e3133e6b4f24772138)
4. done in [deterministic bots](https://github.com/delvtech/elf-simulations/commit/8e1b296945756885ff9a8b0329d766e9c0687c9f)
5. done in [fix: save old balance before update](https://github.com/delvtech/elf-simulations/commit/baa7a2c75f3405be462074d24087ea07f492c09e)
6. done in [fix: log wallet address as string](https://github.com/delvtech/elf-simulations/commit/94ed0a471691051f6eeeecbe88487d3ac70455ff)
7. done in [allow passing args to run_hyperdrive_agents](https://github.com/delvtech/elf-simulations/commit/6805d78ec22b62e049a43cc92b10f9e1adaff775), [allow kwarg overrides to config](https://github.com/delvtech/elf-simulations/commit/12f1416e4c497c00dc176ec1bc91e0ecafa70e61), and [allow custom trade_list](https://github.com/delvtech/elf-simulations/commit/8778e14c1598f4b3d34fa83f86f47a06836706d5)
8. done in [tldr instructions](https://github.com/delvtech/elf-simulations/commit/064d44108a0c84b998a9de534168b5288ae1dfbb) and [add run bots workflow](https://github.com/delvtech/elf-simulations/commit/b12d54cc28785826b3f5f5d122640c96f34a85b5)

**Comment by dpaiton** [comment]
Closing since this is marked as Done.
